{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "olliemeow.serviceAccountName" . }}
  labels:
{{ include "olliemeow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "olliemeow.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "olliemeow.serviceAccountName" . }}
{{- end -}}
