{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "olliemeow.serviceAccountName" . }}
  labels:
{{ include "olliemeow.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get","list", "watch"]
{{- end -}}
