{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olliemeow.serviceAccountName" . }}
  labels:
{{ include "olliemeow.labels" . | nindent 4 }}
{{- end -}}
